# Generated by Django 4.1.6 on 2023-02-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handleName', models.CharField(max_length=150)),
                ('handle_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.domain')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='handles',
            field=models.ManyToManyField(to='main.handle'),
        ),
    ]
