# Generated by Django 4.1.6 on 2023-02-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostingSite', models.CharField(max_length=300)),
                ('participantsRegistered', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('timing', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('contestsHeld', models.IntegerField(default=0)),
            ],
        ),
    ]
