# Generated by Django 4.1.6 on 2023-02-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_handle_user_handles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contest_history',
            field=models.ManyToManyField(null=True, related_name='all_contests', to='main.contest'),
        ),
    ]
