# Generated by Django 4.1.6 on 2023-02-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='streak',
            new_name='user_points',
        ),
    ]
