# Generated by Django 4.1.6 on 2023-02-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contest_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='domain_contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.domain'),
        ),
        migrations.AddField(
            model_name='user',
            name='contest_history',
            field=models.ManyToManyField(related_name='all_contests', to='main.contest'),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.ManyToManyField(to='main.domain'),
        ),
        migrations.AddField(
            model_name='user',
            name='recentActivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_activity', to='main.contest'),
        ),
    ]
