# Generated by Django 4.1.6 on 2023-02-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_contest_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contest_history',
            field=models.ManyToManyField(blank=True, related_name='all_contests', to='main.contest'),
        ),
    ]
