# Generated by Django 4.1.6 on 2023-02-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_streak_user_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='ref',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
