# Generated by Django 4.1.6 on 2023-02-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_points_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='handle',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
